# Generated by Django 4.0.1 on 2022-02-18 21:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Passive')], db_index=True, default=1)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=225)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(upload_to='media/video_cover_images/')),
                ('video', models.FileField(upload_to='media/videos')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'In Progress'), (3, 'Completed'), (4, 'Failed')], db_index=True, default=1)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
