# Generated by Django 4.0.1 on 2022-02-27 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "content",
            "0001_initial",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="created_by",
            field=core.fields.CreatingUserField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_%(app_label)s_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="tags",
            field=models.ManyToManyField(to="content.Tag"),
        ),
        migrations.AddField(
            model_name="comment",
            name="commented_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="content.content",
            ),
        ),
    ]
